---
# tasks file for netzwirt.simple-pki
# create server requests and certs

- name: create server requests
  shell: PKI_FQDN="{{ item.fqdn }}"
      PKI_SAN="DNS:{{ item.fqdn }}{% if item.altnames is defined %},DNS:{{item.altnames|join(',DNS:')}}{% endif %}" openssl req -new
      -config {{ simplepki_conf_dir }}/server.conf
      -out {{ item.fqdn }}{{ simplepki_file_ext_csr }}
      -keyout {{ item.fqdn }}{{ simplepki_file_ext_key }}
    creates="{{ item.fqdn }}{{ simplepki_file_ext_key }}"
    executable=/bin/bash
    chdir="{{ simplepki_certs_dir }}"
  with_items: "{{ simplepki_server_certs }}"


- name: sign server requests
  shell: openssl ca
      -config {{ simplepki_conf_dir }}/{{ simplepki_signing_ca_name }}.conf
      -in {{ item.fqdn }}{{ simplepki_file_ext_csr }}
      -out {{ item.fqdn }}{{ simplepki_file_ext_crt }}
      -extensions server_ext
      -batch
    creates="{{ item.fqdn }}{{ simplepki_file_ext_crt }}"
    executable=/bin/bash
    chdir="{{ simplepki_certs_dir }}"
  with_items: "{{ simplepki_server_certs }}"


- name: protect server keys
  file: 
    path: "{{ simplepki_certs_dir }}/{{ item.fqdn }}{{ simplepki_file_ext_key }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0400
  with_items: "{{ simplepki_server_certs }}"


- name: fetch server keys
  fetch:
    src: "{{ simplepki_certs_dir }}/{{ item.fqdn }}{{ simplepki_file_ext_key }}"
    dest: "{{ simplepki_storage_servers_keys }}/{{ item.fqdn }}{{ simplepki_file_ext_key }}"
    flat: yes
  with_items: "{{ simplepki_server_certs }}"
  when: simplepki_fetch_pki_servers_keys


- name: fetch server certs
  fetch:
    src: "{{ simplepki_certs_dir }}/{{ item.fqdn }}{{ simplepki_file_ext_crt }}"
    dest: "{{ simplepki_storage_servers_certs }}/{{ item.fqdn }}{{ simplepki_file_ext_crt }}"
    flat: yes
  with_items: "{{ simplepki_server_certs }}"
  when: simplepki_fetch_pki_servers_certs


- name: register server pem
  shell: cat "{{ simplepki_certs_dir }}/{{ item.fqdn }}{{ simplepki_file_ext_crt }}" && 
         cat "{{ simplepki_certs_dir }}/{{ item.fqdn }}{{ simplepki_file_ext_key }}" && 
         cat "{{ simplepki_chained_ca_cert }}"
  with_items: "{{ simplepki_server_certs }}"
  changed_when: False
  when: simplepki_fetch_pki_servers_pem
  register: _server_certs


- name: generate server pem
  template: 
    src: "pem.j2" 
    dest: "{{ simplepki_certs_dir }}/{{ item.item.fqdn }}.pem" 
    owner: root 
    group: root
    mode: 0400
  with_items: "{{ _server_certs.results }}"
  when: simplepki_fetch_pki_servers_pem


- name: fetch server pem
  fetch: 
    src: "{{ simplepki_certs_dir }}/{{ item.fqdn }}.pem"
    dest: "{{ simplepki_storage_servers_pem }}/{{ item.fqdn }}.pem"
    flat: yes
  with_items: "{{ simplepki_server_certs }}"
  when: simplepki_fetch_pki_servers_pem


  
